### ISSUE TITLE
We have no documentation

### ISSUE THREAD

**Issue by skyegallup** [1777TheVikings/DeepSpaceVision#5]
### Summary

This codebase may be confusing for those unfamiliar with it. Documentation comments would help others understand how everything works.

### Analysis

- This project currently has no documentation.

- [Javadoc comments](http://www.drjava.org/docs/user/ch10.html) are nicely integrated into Visual Studio Code, so we should use those.

- This codebase is probably not permanent enough to justify building documents using the `javadoc` tool, so VSCode integration should be enough.

**Comment by terpyderp** [comment]
terpyderp

**Comment by terpyderp** [comment]
I've added more comments to Processor.java in the Henry-Edition branch
